- name: Write Kayobe Automation Workflows
  hosts: localhost
  gather_facts: true
  roles:
    - role: kayobe_automation_workflows
      vars:
        output_directory: "{{ ansible_facts.env.KAYOBE_CONFIG_PATH }}/../../.github/workflows"
        kayobe_arguments:
          KAYOBE_ENVIRONMENT: ci-multinode