name: Run overcloud inventory discover

on:
  workflow_dispatch:
    inputs:
      kayobeLimit:
        description: |
          The ansible limit to use when running kayobe playbooks.
      kayobeTags:
        description: |
          The ansible tags to use when running kayobe playbooks.

jobs:
  overcloud-inventory-discover:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout kayobe config
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Symlink source checkout to expected location
        run: sudo ln -s $PWD /src

      - name: Run overcloud inventory discover
        run: |
          /src/.automation/pipeline/overcloud-inventory-discover.sh
        env:
          KAYOBE_ENVIRONMENT: 'ci-multinode'
          KAYOBE_TAGS: '${{ github.event.inputs.kayobeTags }}'
          KAYOBE_LIMIT: '${{ github.event.inputs.kayobeLimit }}'
          KAYOBE_AUTOMATION_PR_TARGET_BRANCH: '${{ github.event.ref }}'
          KAYOBE_AUTOMATION_PR_REMOTE: 'https://${KAYOBE_AUTOMATION_PR_GITHUB_USER}:${KAYOBE_AUTOMATION_PR_AUTH_TOKEN}@github.com/${{ github.repository }}'
          KAYOBE_AUTOMATION_PR_GITHUB_USER: '${{ github.actor }}'
          KAYOBE_AUTOMATION_PR_AUTH_TOKEN: '${{ github.token }}'
          KAYOBE_AUTOMATION_PR_TYPE: 'github'
          KAYOBE_AUTOMATION_PR_TITLE: '[kayobe-automation] ${{ github.workflow }} #${{ github.run_id }}'
          KAYOBE_AUTOMATION_PR_URL: 'https://api.github.com/repos/${{ github.repository }}/pulls'
          HOME: '/stack'
